"""Add delivery type, region, and buffer ledger

Revision ID: 4d6db76d758e
Revises: 705181905fd8
Create Date: 2026-10-03 11:52:57.431392

"""

from collections.abc import Sequence

import geoalchemy2
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4d6db76d758e"
down_revision: str | Sequence[str] | None = "705181905fd8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "regions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column(
            "geometry",
            geoalchemy2.types.Geometry(
                geometry_type="MULTIPOLYGON",
                srid=4326,
                dimension=2,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "buffer_ledger",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("transaction_id", sa.UUID(), nullable=False),
        sa.Column("tonnes", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column(
            "status",
            sa.Enum("pending", "active", "retired", name="bufferstatus"),
            nullable=False,
        ),
        sa.Column("notes", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["transaction_id"],
            ["transactions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    postgresql.ENUM("issued", "forward", name="deliverytype").create(op.get_bind())
    op.add_column(
        "credit_batches",
        sa.Column(
            "delivery_type",
            sa.Enum("issued", "forward", name="deliverytype"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("credit_batches", "delivery_type")
    postgresql.ENUM(name="deliverytype").drop(op.get_bind())
    op.drop_table("buffer_ledger")
    postgresql.ENUM(name="bufferstatus").drop(op.get_bind())
    op.drop_table("regions")
    # ### end Alembic commands ###
