"""Initial migration

Revision ID: 705181905fd8
Revises: 
Create Date: 2026-10-03 11:47:19.166492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import geoalchemy2

# revision identifiers, used by Alembic.
revision: str = '705181905fd8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('aggregator', 'buyer', 'admin', name='userrole'), nullable=False),
    sa.Column('company_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('credit_batches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('aggregator_id', sa.UUID(), nullable=False),
    sa.Column('farm_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('standard', sa.Enum('verra', 'gold_standard', name='creditstandard'), nullable=False),
    sa.Column('vintage_year', sa.String(), nullable=False),
    sa.Column('total_tco2e', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('available_tco2e', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('price_per_tonne', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('status', sa.Enum('draft', 'listed', 'sold_out', 'retired', name='creditstatus'), nullable=False),
    sa.Column('co_benefits', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('scope_3_region', sa.String(), nullable=True),
    sa.Column('scope_3_geom', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('registry_serial_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['aggregator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('farms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('aggregator_id', sa.UUID(), nullable=False),
    sa.Column('farmer_name', sa.String(), nullable=False),
    sa.Column('polygon', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('total_hectares', sa.Float(), nullable=False),
    sa.Column('crop_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['aggregator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('buyer_id', sa.UUID(), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('tonnes_purchased', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('buffer_tonnes', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('net_tonnes', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('payment_status', sa.Enum('pending', 'partially_paid', 'completed', name='paymentstatus'), nullable=False),
    sa.Column('milestones', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('buffer_pool_allocation', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['credit_batches.id'], ),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    op.drop_table('farms')
    op.drop_table('credit_batches')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    postgresql.ENUM(name='paymentstatus').drop(op.get_bind())
    postgresql.ENUM(name='creditstandard').drop(op.get_bind())
    postgresql.ENUM(name='creditstatus').drop(op.get_bind())
    postgresql.ENUM(name='userrole').drop(op.get_bind())
    # ### end Alembic commands ###
